:schedule:
  PromotionJob:
    cron: '0 9 * * 1'
  FetchapiJob:
    cron: '0 13 * * 1,3'
  FetchapibasketJob:
    cron: '0 12 * * 1'
  FetchapibaskettomorrowJob:
    cron: '0 13 * * 2,3,4,5,6'
  UpdatebasketpointsJob:
    cron: '0 14 * * 2,3,4,5,6'
  FetchapilastJob:
    cron: '0 11 * * 5'
  ResultsJob:
    cron: '30 21 * * *'
  ResultsbasketJob:
    cron: '30 00 * * *'
  ResultsbaskettodayJob:
    cron: '30 4 * * *'
