:schedule:
  season_job:
    cron: '0 6 * * MON'
    class: SeasonJob

:schedule:
  fetchapi_job:
    cron: '0 7 * * MON,WED'
    class: FetchapiJob

:schedule:
  fetchapilast_job:
    cron: '0 19 * * FRI'
    class: FetchapilastJob
