:schedule:
  PromotionJob:
    cron: '0 14 * * 1'
  FetchapiJob:
    cron: '0 15 * * 1'
  FetchApiOneDayJob:
    cron: '30 5 * * 3,6,7'
  FetchapilastJob:
    cron: '30 5 * * 2,4,5'
  FetchapibasketJob:
    cron: '0 15 * * 1'
  FetchapibaskettomorrowJob:
    cron: '0 8 * * 2,3,4,5,6'
  UpdatebasketpointsJob:
    cron: '0 14 * * 2,3,4,5,6'
  ResultsJob:
    cron: '30 22 * * *'
  ResultsYesterdayJob:
    cron: '30 23 * * *'
  ResultsbasketJob:
    cron: '30 1 * * *'
  ResultsbaskettodayJob:
    cron: '30 8 * * *'
  PlayermouvJob:
    cron: '0 */6 * * *'
