
:schedule:
  season_job:
    cron: '0 16 * * MON'
    class: SeasonJob

:schedule:
  fetchapi_job:
    cron: '0 17 * * MON,WED'
    class: FetchapiJob

:schedule:
  fetchapilast_job:
    cron: '0 18 * * MON'
    class: FetchapilastJob
