:schedule:
  PromotionJob:
    cron: '0 14 * * 1'
  FetchapiJob:
    cron: '0 15 * * 1'
  FetchapionedayJob:
    cron: '30 5 * * 3,6,7'
  FetchapilastJob:
    cron: '30 5 * * 2,4,5'
  FetchapibasketJob:
    cron: '0 12 * * 1'
  FetchapibaskettomorrowJob:
    cron: '0 13 * * 2,3,4,5,6'
  UpdatebasketpointsJob:
    cron: '0 14 * * 2,3,4,5,6'
  ResultsJob:
    cron: '50 22 * * *'
  ResultsbasketJob:
    cron: '30 1 * * *'
  ResultsbaskettodayJob:
    cron: '30 4 * * *'
