:schedule:
  PromotionJob:
    cron: '0 13 * * 1'
  FetchapiJob:
    cron: '0 14 * * 1'
  FetchApiOneDayJob:
    cron: '30 4 * * 3,6,7'
  FetchapilastJob:
    cron: '30 4 * * 2,4,5'
  FetchapibasketJob:
    cron: '0 14 * * 1'
  FetchapibaskettomorrowJob:
    cron: '0 7 * * 2,3,4,5,6'
  UpdatebasketpointsJob:
    cron: '0 13 * * 2,3,4,5,6'
  ResultsJob:
    cron: '20 21 * * *'
  ResultsYesterdayJob:
    cron: '30 22 * * *'
  ResultsbasketJob:
    cron: '0 6 * * *'
  ResultsbaskettodayJob:
    cron: '30 6 * * *'
  PlayermouvJob:
    cron: '0 */6 * * *'
