:schedule:
  PromotionJob:
    cron: '0 12 * * 1'
  FetchapiJob:
    cron: '0 13 * * 1,2'
  FetchapibasketJob:
    cron: '0 14 * * 1'
  FetchapibaskettomorrowJob:
    cron: '0 15 * * 2,3,4,5,6'
  UpdatebasketpointsJob:
    cron: '0 16 * * 2,3,4,5,6'
  FetchapilastJob:
    cron: '0 11 * * 5'
  ResultsJob:
    cron: '0 0 * * *'
  RecalcpointsJob:
    cron: '0 1 * * *'
  ResultsbasketJob:
    cron: '0 7,23 * * *'
