:schedule:
  SeasonJob:
    cron: '0 12 * * MON'
  FetchapiJob:
    cron: '0 12 * * MON,WED'
  FetchapilastJob:
    cron: '0 11 * * FRI'
  ResultsJob:
    cron: '0 24 * * *'
  RecalcpointsJob:
    cron: '0 1 * * *'
