:schedule:
  season_job:
    cron: '0 9 * * MON'
    class: SeasonJob

:schedule:
  fetchapi_job:
    cron: '0 8 * * MON,WED'
    class: FetchapiJob

:schedule:
  fetchapilast_job:
    cron: '* * * * *'
    class: FetchapilastJob
