season:
  class: "SeasonJob"
  every: "1.week"
  at: "Mon 6:00"
  tz: "Europe/Paris"

fetchapi:
  class: "FetchapiJob"
  every: "1.day"
  at: "7:00"
  tz: "Europe/Paris"

fetchapilast:
  class: "FetchapilastJob"
  every: "1.week"
  at: "Fri 6:00"
  tz: "Europe/Paris"
